### ISSUE TITLE
nz-table下一页，表格的滚动条没跳到顶部

### ISSUE THREAD

**Issue by s641135196** [1-2-3/zorro-sharper#1]
请问大神有什么好的解决方案吗，官方demo都有这问题，  设置了nzScroll= {y:''}才会有这问题
![image](https://user-images.githubusercontent.com/8079013/64063167-4ed4c780-cc23-11e9-91b7-b767ad3f7ebd.png)

**Comment by 1-2-3** [comment]
> 请问大神有什么好的解决方案吗，官方demo都有这问题， 设置了nzScroll= {y:''}才会有这问题
> ![image](https://user-images.githubusercontent.com/8079013/64063167-4ed4c780-cc23-11e9-91b7-b767ad3f7ebd.png)

试了下 nzTable 确实有你说的问题，我已经在 1.1.1 版为 nsAutoHeightTable 指令增加了变更当前页码时滚动条自动回到顶部的功能。ng-alain 的 st 表格没有这个问题。
