### ISSUE TITLE
missing depedencies

### ISSUE THREAD

**Issue by agborkowski** [1-2-3/zorro-sharper#5]
i had error like this:

The target entry-point "zorro-sharper" has missing dependencies:
 - date-fns/formatDistanceToNow

i have already installed "ng-zorro-antd": "^11.1.0",

**Comment by agborkowski** [comment]
solved by install extra packages:
npm i @nebular/date-fns
npm i -S date-fns@2 
for what that dependencies is needed?

**Comment by 1-2-3** [comment]
I tried deleting the node_modules folder and re-executing `npm install`, no error message. I checked `package-lock.json` file and found that the date-fns should be dependent on the Zorro component library.

**Comment by agborkowski** [comment]
youp it was some problem with node_modules
