### ISSUE TITLE
Update to angular 12 and ng-zorro 12

### ISSUE THREAD

**Issue by celluj34** [1-2-3/zorro-sharper#6]
Hello;

I am using your library, but I have upgraded to version 12. Can you release a version that is compatible?

Thank you!

**Comment by x157123** [comment]
Hello;

I am using your library, but I have upgraded to version 13. Can you release a version that is compatible?

Thank you!

**Comment by 1-2-3** [comment]
ok i'll do it this weekend

**Comment by 1-2-3** [comment]
@x157123 @celluj34 I released two new versions, 12.0.0 and 13.0.0, corresponding to ng12 & zorro12 and ng13 & zorro13 respectively

**Comment by celluj34** [comment]
Fantastic, thank you!
